<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KIRAN" ignored="0" name="Test2" tests="5" failures="1" timestamp="2023-04-30T18:10:37 IST" time="0.64" errors="0">
  <testcase name="sampleTest1" time="0.209" classname="tests.SampleTest">
    <skipped/>
  </testcase> <!-- sampleTest1 -->
  <testcase name="sampleTest1" time="0.015" classname="tests.SampleTest">
    <failure type="java.lang.AssertionError" message="Failed SampleTest1 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed SampleTest1 expected [true] but found [false]
at tests.SampleTest.sampleTest1(SampleTest.java:16)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- sampleTest1 -->
  <testcase name="sampleTest2" time="0.003" classname="tests.SampleTest"/>
  <testcase name="sampleTest3" time="0.007" classname="tests.SampleTest"/>
  <testcase name="sampleTest4" time="0.005" classname="tests.SampleTest"/>
</testsuite> <!-- Test2 -->
