<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-KIRAN" failures="1" tests="2" name="Test2" time="8.773" errors="0" timestamp="2023-04-24T01:29:03 IST">
  <testcase classname="tests.LoginTest" name="verifyInValidLogin" time="0.482">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at pages.LoginPage.login(LoginPage.java:39)
at tests.LoginTest.verifyInValidLogin(LoginTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyInValidLogin -->
  <testcase classname="tests.LoginTest" name="verifyValidLoginLogout" time="1.429"/>
  <testcase classname="tests.LoginTest" name="verifyValidLogin" time="0.0">
    <ignored/>
  </testcase> <!-- verifyValidLogin -->
</testsuite> <!-- Test2 -->
