<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KIRAN" ignored="1" name="Test2" tests="2" failures="1" timestamp="2023-04-25T01:20:28 IST" time="9.666" errors="0">
  <testcase name="verifyInValidLogin" time="0.503" classname="tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at pages.LoginPage.login(LoginPage.java:41)
at tests.LoginTest.verifyInValidLogin(LoginTest.java:73)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyInValidLogin -->
  <testcase name="verifyValidLoginLogout" time="1.288" classname="tests.LoginTest"/>
  <testcase name="verifyValidLogin" time="0.0" classname="tests.LoginTest">
    <ignored/>
  </testcase> <!-- verifyValidLogin -->
</testsuite> <!-- Test2 -->
